services:
  webapp:
    image: samathgamlath1111/helaconnectwebappimg:1.0.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=helaconnectappdb;User=appuser;Password=appuserpassword
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"
    networks:
      - helaconnect-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: helaconnectappdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpassword
    ports:
      - "3307:3306"
    networks:
      - helaconnect-network
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  helaconnect-network:
    driver: bridge

volumes:
  db-data:
