services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: helaconnectappdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpassword
    ports:
      - "3306:3306"
    networks:
      - helaconnect-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=helaconnectappdb;User=appuser;Password=appuserpassword
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - helaconnect-network

networks:
  helaconnect-network:
    driver: bridge
